backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "texts"
    label: "Texts"
    folder: "texts/00/00"
    create: true
    nested:
      depth: 100
    meta: { path: { widget: string, label: 'Path', index_file: 'data' } }
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title Translation", name: "titleTranslation", widget: "string", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "string", required: false }
      - { label: "Language Code", name: "language", widget: "string", required: false }

  - name: "authors"
    label: "Authors"
    folder: "authors"
    create: true
    identifier_field: "name"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Birth Year", name: "birthYear", widget: "string", required: false }
      - { label: "Death Year", name: "deathYear", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }

  - name: "works"
    label: "Works"
    folder: "works"
    create: true
    identifier_field: "title"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
